### ISSUE TITLE
Spring bus implementation for internal framework traffic

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#3187]
### Goal

Communication between different internal framework components is tightly coupled, by implementing spring bus it will use the spring bus as a pub sub "eventbus" to communicate

### Description

The communication using the springbus will decouple the different framework components, this will simplify the code. it will also alow the next step: externalizing the spring bus between nodes.

### Tasks 
- [x] #3615
- [x] #3845
- [x] #3901
- [x] Create DTO's to use over the bus
- [x] GUI API spring bus
- [ ] Ladybug-API via spring bus
- [ ] Ensure the bus is extensible (via plugable interface) to use over multiple nodes
- [x] Fix ConfigurationUtils, remove literals from queries
- [x] Refactor ConfigurationUtils use ApplicationContext
- [x] Remove ApplicationMetrics (information is now part of native Spring)
- [x] Add Bus selector to only route messages when bus is in state ACTIVE
- [x] Refactor getIbisHealth endpoint to avoid using IbisManager to detect application
- [x] Avoid ConcurrentModificationExceptions inTransactionManagerType.close method
- [x] Cleanup IbisManagerMock
- [x] #5286
- [x] #4757
