### ISSUE TITLE
Improve larva 

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#3470]
### Goal
make larva less dependent on servlet and cleanup code

### Tasks 
- [ ] task1
- [ ] task2

**Comment by nielsm5** [comment]
- [ ] Find out if it's possible to use a YML schema, with autocomplete.
- [ ] Create an example yml structure.
- [ ] Create a discussion with the community to find out if it actually solves their problems.
