### ISSUE TITLE
JDK 8 reached it's end of premier support in March 2022

### ISSUE THREAD

**Issue by nielsm5** [ibissource/iaf#3503]
**Describe the issue**
Since Oracle had officially stopped supporting Java 8 we need to start thinking about our upgrade path.
Java 11 EOL is coming up in September 2023 so I don't think it's wise to go down that route. The next LTS candidate is Java 17, which is supported till 2026. See the [Java Support Roadmap](https://www.oracle.com/java/technologies/java-se-support-roadmap.html).

Spring has already been supporting Java 17 and is recommending users to also start adopting Java 17 as of version 5.3.x.
See [Spring Java 17 baseline](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6) and [Spring Java 17 adoption](https://spring.io/blog/2022/03/28/an-update-on-java-17-adoption).

It is important that we finish epic #3405 to avoid dependency collisions between the Javax and Jakarta namespace. Right now we've almost fully adopted Jakarta, while still using the Javax namespaces.

From what I can see CXF is the remaining dependency that is locked in on the Javax namespace. 
We will have to;
- [ ] LCM CXF to version 4.x (see https://github.com/apache/cxf/pull/912)
- [x] Implement the Jakarta SOAP-API & WS-API
- [ ] LCM our SAAJ implementation (which is currently done though a servicemix bundle)

**Reporter**
Niels

**Comment by nielsm5** [comment]
https://spring.io/blog/2022/11/16/spring-framework-6-0-goes-ga

**Comment by nielsm5** [comment]
Full new comprehensive list: #5637
